name: CICD

on:
  pull_request:
    branches: ["main"]
    types:
      - opened
      - closed
      - reopened
      - edited
      - synchronize

jobs:
  swift-ci:
    name: SwiftCI
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1.20.0
      with:
        swift-version: "5.7.0"

    - name: Run SwiftCI
      run: |
        echo "::group::Swift Run"
        swift run --package-path .github/workflows/cicd
      env:
        APP_STORE_CONNECT_KEY_P8: ${{ secrets.APP_STORE_CONNECT_KEY_P8 }}
        CERTIFICATE_P12: ${{ secrets.CERTIFICATE_P12 }}
        CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
